- hosts: all
  gather_facts: no
  vars:
    - ssh_keys_url: "https://github.com/naps62.keys"
    - ssh_port: "{{ ansible_port }}"
  roles:
    # - role: alexinthesky.secure-docker-daemon
    #   dds_host: "*.mtgsear.ch"
    #   dds_country: "PT"
    #   dds_state: "Braga"
    #   dds_locality: "Braga"
    #   dds_organization: ""
    #   dds_passphrase: "{{ lookup('env', 'MTGSEARCH_DOCKER_TLS_PASSPHRASE') }}"
    #   dds_restart_docker: true
    - role: docker-tls-service
    - common
    # - alternate_ssh_port
