- name: Correct ssh keys are authorized
  authorized_key:
    state: present
    user: root
    key: "{{ item }}"
  with_items: "{{ ssh_keys_url }}"

- name: SSH configuration disables password authentication
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "(# )?PasswordAuthentication (no|yes)"
    line: "PasswordAuthentication no"
  notify: Restart SSH

